AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  # See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  # for more info to see how to tune the lambda function configs based on your use case.
  GreenGrassHWFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: com.home.amazon.iot.lamnda.GreenGrassHWFunction::handleRequest
      Timeout: 3
      MemorySize: 128
      CodeUri: .
      AutoPublishAlias: Greengrass

  CollectDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: com.home.amazon.iot.lamnda.CollectDataFunction::handleRequest
      Timeout: 3
      MemorySize: 128
      CodeUri: .
      AutoPublishAlias: Greengrass
      Environment:
        Variables:
          SendDataTask_path: /test
          SendDataTask_topic: greengrass/java/data

  SubscribeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: com.home.amazon.iot.lamnda.SubscribeFunction::handleRequest
      Timeout: 3
      MemorySize: 128
      CodeUri: .
      AutoPublishAlias: Greengrass