AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:

  SubscribeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: com.home.amazon.iot.lamnda.SubscribeFunction::handleRequest
      Timeout: 3
      MemorySize: 128
      CodeUri: .
      AutoPublishAlias: Greengrass
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt MessageQueue.QueueName
      Environment:
        Variables:
          QueueUrl: !Ref MessageQueue

  MessageQueue:
    Type: AWS::SQS::Queue

  MessageQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MessageQueue
      PolicyDocument:
        Statement:
          - Action:
              - 'SQS:SendMessage'
            Effect: 'Allow'
            Resource: !GetAtt MessageQueue.Arn
            Principal:
              AWS:
                - !Ref AWS::AccountId